### PR TITLE
Update yarn dependencies

### PR DESCRIPTION
**Pull request by paguos**
Addresses security alert caused by `fstream` dependency.

### CODE REVIEW

**Comment by dakingha69** [comment]
hmm why is the `test_contracts` job failing? also how did you resolve the vulnerability? just run `yarn install`?

**Comment by paguos** [comment]
Because somehow is trying to test in a network called `develop`, but there is only one called `development` 😕

**Comment by dakingha69** [comment]
No `develop` should be the internal dev environment of truffle... Not a network that we configured

**Comment by paguos** [comment]
`Unknown network "develop". See your Truffle configuration file for available networks.`

**Comment by dakingha69** [comment]
yeah seems to be an issue with the updated truffle version.

**Pull request merged**
